// Generated by scripts/generate-recovery-source.mjs.
// Do not edit this file by hand.
export const RECOVERY_SOURCE_FILE_COUNT = 623;
export const RECOVERY_SOURCE_SHA256 = "2240d0625bd3b09634bb28451a2ae5e8a72024fd5011759231d2c4ff6464ec5e";
export const RECOVERY_SOURCE_RELEASE = "working-tree";
export const RECOVERY_SOURCE_ASSET_PATH = "/recovery/WHIZZUP_source.zip";
