// Generated by scripts/generate-recovery-source.mjs.
// Do not edit this file by hand.
export const RECOVERY_SOURCE_FILE_COUNT = 604;
export const RECOVERY_SOURCE_SHA256 = "fb3c1c5c8ed2e44510bb768093c8954072790f68bc13b1f0fd81ed0e67c048fd";
export const RECOVERY_SOURCE_RELEASE = "working-tree";
export const RECOVERY_SOURCE_ASSET_PATH = "/recovery/WHIZZUP_source.zip";
