// Generated by scripts/generate-recovery-source.mjs.
// Do not edit this file by hand.
export const RECOVERY_SOURCE_FILE_COUNT = 620;
export const RECOVERY_SOURCE_SHA256 = "1dc1c13219ad80ab6983c58ed40cc4cc5718f6e92ee4b75c65e54ae18769bc26";
export const RECOVERY_SOURCE_RELEASE = "working-tree";
export const RECOVERY_SOURCE_ASSET_PATH = "/recovery/WHIZZUP_source.zip";
