import "server-only";

import {
  createHash,
  pbkdf2Sync,
  randomBytes,
  timingSafeEqual,
} from "node:crypto";
import { cookies } from "next/headers";
import { getD1 } from "../db";

export const LOCAL_AUTH_COOKIE = "whizzup_local_session";
export const LOCAL_AUTH_ITERATIONS = 100_000;
const SESSION_HOURS = 12;
const REMEMBER_DAYS = 30;
let localAuthSchemaPromise: Promise<void> | null = null;

export function ensureLocalAuthSchema() {
  if (!localAuthSchemaPromise) {
    const d1 = getD1();
    const statements = [
      "ALTER TABLE members ADD COLUMN IF NOT EXISTS username text",
      "ALTER TABLE members ADD COLUMN IF NOT EXISTS password_hash text",
      "ALTER TABLE members ADD COLUMN IF NOT EXISTS password_salt text",
      "ALTER TABLE members ADD COLUMN IF NOT EXISTS password_iterations integer NOT NULL DEFAULT 210000",
      "ALTER TABLE members ADD COLUMN IF NOT EXISTS failed_login_count integer NOT NULL DEFAULT 0",
      "ALTER TABLE members ADD COLUMN IF NOT EXISTS locked_until timestamptz",
      "CREATE UNIQUE INDEX IF NOT EXISTS members_username_idx ON members (lower(username)) WHERE username IS NOT NULL",
      `CREATE TABLE IF NOT EXISTS member_credentials (
        member_id bigint PRIMARY KEY REFERENCES members(id) ON DELETE CASCADE,
        password_hash text NOT NULL,
        password_salt text NOT NULL,
        password_iterations integer NOT NULL DEFAULT 100000,
        password_set_at timestamptz NOT NULL DEFAULT now(),
        failed_attempts integer NOT NULL DEFAULT 0,
        locked_until timestamptz,
        updated_at timestamptz NOT NULL DEFAULT now()
      )`,
      `CREATE TABLE IF NOT EXISTS local_auth_sessions (
        token_hash text PRIMARY KEY,
        member_id bigint NOT NULL REFERENCES members(id) ON DELETE CASCADE,
        expires_at timestamptz NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now(),
        last_seen_at timestamptz NOT NULL DEFAULT now()
      )`,
      "CREATE INDEX IF NOT EXISTS local_auth_sessions_member_idx ON local_auth_sessions (member_id, expires_at)",
      "ALTER TABLE member_password_reset_requests ADD COLUMN IF NOT EXISTS email text NOT NULL DEFAULT ''",
      "ALTER TABLE member_password_reset_requests ADD COLUMN IF NOT EXISTS resolved_by bigint",
      `CREATE TABLE IF NOT EXISTS member_account_archives (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        original_member_id bigint NOT NULL,
        member_json text NOT NULL,
        archived_by bigint NOT NULL,
        archived_at timestamptz NOT NULL DEFAULT now()
      )`,
      "REVOKE ALL ON member_credentials FROM anon, authenticated",
      "REVOKE ALL ON local_auth_sessions FROM anon, authenticated",
      "REVOKE ALL ON member_account_archives FROM anon, authenticated",
    ];
    localAuthSchemaPromise = d1
      .prepare(
        `SELECT
           to_regclass('public.local_auth_sessions') IS NOT NULL AS has_sessions,
           to_regclass('public.member_account_archives') IS NOT NULL AS has_archives,
           to_regclass('public.member_credentials') IS NOT NULL AS has_credentials,
           COUNT(*) FILTER (
             WHERE column_name IN (
               'username', 'password_hash', 'password_salt',
               'password_iterations', 'failed_login_count', 'locked_until'
             )
           ) AS member_auth_columns,
           (
             SELECT COUNT(*)
             FROM information_schema.columns reset_columns
             WHERE reset_columns.table_schema = 'public'
               AND reset_columns.table_name = 'member_password_reset_requests'
               AND reset_columns.column_name IN ('email', 'resolved_by')
           ) AS reset_request_columns
         FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = 'members'`,
      )
      .first<{
        has_sessions: boolean;
        has_archives: boolean;
        has_credentials: boolean;
        member_auth_columns: number | string;
        reset_request_columns: number | string;
      }>()
      .then(async (schema) => {
        const ready =
          Boolean(schema?.has_sessions) &&
          Boolean(schema?.has_archives) &&
          Boolean(schema?.has_credentials) &&
          Number(schema?.member_auth_columns ?? 0) === 6 &&
          Number(schema?.reset_request_columns ?? 0) === 2;
        if (!ready) {
          await d1.batch(statements.map((statement) => d1.prepare(statement)));
        }
      })
      .then(() => undefined)
      .catch((error) => {
        localAuthSchemaPromise = null;
        throw error;
      });
  }
  return localAuthSchemaPromise;
}

export async function ensureDirectAuthReady() {
  await ensureLocalAuthSchema();
  return getD1();
}

export function normalizeUsername(value: unknown) {
  return String(value ?? "").trim().toLowerCase();
}

export function validateUsername(username: string) {
  return /^[a-z0-9][a-z0-9._-]{3,29}$/.test(username);
}

export function validatePassword(password: string) {
  return (
    password.length >= 8 &&
    password.length <= 128 &&
    /[A-Za-z]/.test(password) &&
    /[0-9]/.test(password)
  );
}

export function hashPassword(
  password: string,
  salt = randomBytes(16).toString("base64url"),
) {
  const hash = pbkdf2Sync(
    password,
    Buffer.from(salt, "utf8"),
    LOCAL_AUTH_ITERATIONS,
    32,
    "sha256",
  ).toString("base64url");
  return { hash, salt, iterations: LOCAL_AUTH_ITERATIONS };
}

export async function setMemberPassword(memberId: number, password: unknown) {
  const value = String(password ?? "");
  if (!validatePassword(value)) {
    throw new Error("비밀번호는 영문과 숫자를 포함해 8자 이상 입력해 주세요.");
  }
  const { hash, salt, iterations } = hashPassword(value);
  const d1 = await ensureDirectAuthReady();
  await d1.transaction(async (transaction) => {
    await transaction
      .prepare(
        `INSERT INTO member_credentials (
           member_id, password_hash, password_salt, password_iterations,
           password_set_at, failed_attempts, locked_until, updated_at
         ) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, 0, NULL, CURRENT_TIMESTAMP)
         ON CONFLICT(member_id) DO UPDATE SET
           password_hash = excluded.password_hash,
           password_salt = excluded.password_salt,
           password_iterations = excluded.password_iterations,
           password_set_at = CURRENT_TIMESTAMP,
           failed_attempts = 0,
           locked_until = NULL,
           updated_at = CURRENT_TIMESTAMP`,
      )
      .bind(memberId, hash, salt, iterations)
      .run();
    await transaction
      .prepare("DELETE FROM local_auth_sessions WHERE member_id = ?")
      .bind(memberId)
      .run();
    await transaction
      .prepare(
        `UPDATE member_password_reset_requests
         SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP
         WHERE member_id = ? AND status = 'pending'`,
      )
      .bind(memberId)
      .run();
  });
}

export function verifyPassword(
  password: string,
  salt: string,
  expectedHash: string,
  iterations = LOCAL_AUTH_ITERATIONS,
) {
  const actual = pbkdf2Sync(
    password,
    Buffer.from(salt, "utf8"),
    iterations,
    32,
    "sha256",
  );
  const expected = Buffer.from(expectedHash, "base64url");
  return actual.length === expected.length && timingSafeEqual(actual, expected);
}

export function localMemberEmail(username: string) {
  return `${username}@local.whizzup`;
}

export async function createLocalSession(memberId: number, remember = true) {
  const token = randomBytes(32).toString("base64url");
  const tokenHash = createHash("sha256").update(token).digest("hex");
  const milliseconds = remember
    ? REMEMBER_DAYS * 24 * 60 * 60 * 1000
    : SESSION_HOURS * 60 * 60 * 1000;
  const expiresAt = new Date(Date.now() + milliseconds);
  const d1 = getD1();
  await d1
    .prepare(
      `INSERT INTO local_auth_sessions
       (token_hash, member_id, expires_at, created_at, last_seen_at)
       VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)`,
    )
    .bind(tokenHash, memberId, expiresAt.toISOString())
    .run();
  const store = await cookies();
  store.set(LOCAL_AUTH_COOKIE, token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/",
    expires: expiresAt,
  });
}

export async function deleteLocalSession() {
  const store = await cookies();
  const token = store.get(LOCAL_AUTH_COOKIE)?.value ?? "";
  if (token) {
    const tokenHash = createHash("sha256").update(token).digest("hex");
    await getD1()
      .prepare("DELETE FROM local_auth_sessions WHERE token_hash = ?")
      .bind(tokenHash)
      .run();
  }
  store.delete(LOCAL_AUTH_COOKIE);
}

export async function getLocalAuthIdentity() {
  const token = (await cookies()).get(LOCAL_AUTH_COOKIE)?.value ?? "";
  if (!token) return null;
  const tokenHash = createHash("sha256").update(token).digest("hex");
  const d1 = getD1();
  let row;
  try {
    row = await d1
      .prepare(
        `SELECT m.id, m.username, m.email, m.display_name
         FROM local_auth_sessions s
         JOIN members m ON m.id = s.member_id
         WHERE s.token_hash = ?
           AND s.expires_at > CURRENT_TIMESTAMP
           AND m.status = 'approved'
         LIMIT 1`,
      )
      .bind(tokenHash)
      .first<{
        id: number;
        username: string | null;
        email: string;
        display_name: string;
      }>();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (/does not exist|undefined table|undefined column/i.test(message)) return null;
    throw error;
  }
  if (!row) {
    return null;
  }
  await d1
    .prepare(
      `UPDATE local_auth_sessions
       SET last_seen_at = CURRENT_TIMESTAMP
       WHERE token_hash = ?`,
    )
    .bind(tokenHash)
    .run();
  return {
    memberId: Number(row.id),
    username: String(row.username ?? ""),
    email: String(row.email),
    displayName: String(row.display_name),
  };
}
