import { getD1 } from "../db";

export const QUOTATION_STORAGE_LIMIT_BYTES = 10 * 1024 * 1024 * 1024;
export const QUOTATION_MAX_PDF_BYTES = 20 * 1024 * 1024;
export const QUOTATION_MAX_PAGES = 40;

const createTableSql = `
  CREATE TABLE IF NOT EXISTS quotation_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization TEXT NOT NULL,
    company_name TEXT NOT NULL DEFAULT '',
    quote_amount TEXT NOT NULL DEFAULT '',
    quote_date TEXT NOT NULL DEFAULT '',
    original_name TEXT NOT NULL,
    original_key TEXT NOT NULL UNIQUE,
    original_size BIGINT NOT NULL DEFAULT 0,
    page_keys_json TEXT NOT NULL DEFAULT '[]',
    page_sizes_json TEXT NOT NULL DEFAULT '[]',
    page_count INTEGER NOT NULL DEFAULT 0,
    total_size BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL,
    created_by_name TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )
`;

const createObjectTableSql = `
  CREATE TABLE IF NOT EXISTS quotation_file_objects (
    object_key TEXT PRIMARY KEY,
    content_type TEXT NOT NULL DEFAULT 'application/octet-stream',
    object_size BIGINT NOT NULL DEFAULT 0,
    object_data BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )
`;

type QuotationBucket = {
  put(
    key: string,
    value: ArrayBuffer | ArrayBufferView | Blob | ReadableStream,
    options?: {
      httpMetadata?: { contentType?: string; contentDisposition?: string };
      customMetadata?: Record<string, string>;
    },
  ): Promise<unknown>;
  get(key: string): Promise<{
    body: Blob;
    size: number;
    httpMetadata?: { contentType?: string };
  } | null>;
  delete(keys: string | string[]): Promise<void>;
};

export type QuotationDocumentRow = {
  id: number;
  organization: string;
  company_name: string;
  quote_amount: string;
  quote_date: string;
  original_name: string;
  original_key: string;
  original_size: number;
  page_keys_json: string;
  page_sizes_json: string;
  page_count: number;
  total_size: number;
  created_by: number;
  created_by_name: string;
  created_at: string;
};

async function storedBytes(
  value: ArrayBuffer | ArrayBufferView | Blob | ReadableStream,
) {
  if (value instanceof Blob) {
    return new Uint8Array(await value.arrayBuffer());
  }
  if (value instanceof ArrayBuffer) return new Uint8Array(value);
  if (ArrayBuffer.isView(value)) {
    return new Uint8Array(
      value.buffer.slice(value.byteOffset, value.byteOffset + value.byteLength),
    );
  }
  return new Uint8Array(await new Response(value).arrayBuffer());
}

export function getQuotationBucket() {
  const bucket: QuotationBucket = {
    async put(key, value, options) {
      const bytes = await storedBytes(value);
      const contentType =
        options?.httpMetadata?.contentType || "application/octet-stream";
      await getD1()
        .prepare(
          `INSERT INTO quotation_file_objects (
             object_key, content_type, object_size, object_data, updated_at
           ) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
           ON CONFLICT(object_key) DO UPDATE SET
             content_type = EXCLUDED.content_type,
             object_size = EXCLUDED.object_size,
             object_data = EXCLUDED.object_data,
             updated_at = CURRENT_TIMESTAMP`,
        )
        .bind(key, contentType, bytes.byteLength, bytes)
        .run();
    },
    async get(key) {
      const row = await getD1()
        .prepare(
          `SELECT content_type, object_size, object_data
           FROM quotation_file_objects
           WHERE object_key = ?
           LIMIT 1`,
        )
        .bind(key)
        .first<{
          content_type: string;
          object_size: number;
          object_data: Uint8Array;
        }>();
      if (!row) return null;
      const bytes = Uint8Array.from(row.object_data);
      return {
        body: new Blob([bytes.buffer], { type: row.content_type }),
        size: Number(row.object_size) || bytes.byteLength,
        httpMetadata: { contentType: row.content_type },
      };
    },
    async delete(keys) {
      for (const key of Array.isArray(keys) ? keys : [keys]) {
        await getD1()
          .prepare("DELETE FROM quotation_file_objects WHERE object_key = ?")
          .bind(key)
          .run();
      }
    },
  };
  return bucket;
}

export async function ensureQuotationDocumentsReady() {
  const d1 = getD1();
  await d1.prepare(createTableSql).run();
  await d1.prepare(createObjectTableSql).run();
  await d1
    .prepare(
      `CREATE INDEX IF NOT EXISTS quotation_documents_organization_idx
       ON quotation_documents (organization, created_at)`,
    )
    .run();
  return d1;
}

export function parseStoredStringList(value: string) {
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed)
      ? parsed.map((item) => String(item)).filter(Boolean)
      : [];
  } catch {
    return [];
  }
}

export async function quotationStorageStats(
  d1: Awaited<ReturnType<typeof ensureQuotationDocumentsReady>>,
) {
  const row = await d1
    .prepare(
      `SELECT
         COALESCE(SUM(total_size), 0) AS used_bytes,
         COUNT(*) AS document_count,
         COALESCE(SUM(page_count), 0) AS page_count
       FROM quotation_documents`,
    )
    .first<{
      used_bytes: number;
      document_count: number;
      page_count: number;
    }>();
  const trashed = await d1
    .prepare(
      `SELECT COALESCE(SUM(stored_bytes), 0) AS stored_bytes
       FROM deletion_batches
       WHERE restored_at IS NULL`,
    )
    .first<{ stored_bytes: number }>();
  const trashedBytes = Math.max(0, Number(trashed?.stored_bytes) || 0);
  const usedBytes = Math.max(0, Number(row?.used_bytes) || 0) + trashedBytes;
  const remainingBytes = Math.max(
    0,
    QUOTATION_STORAGE_LIMIT_BYTES - usedBytes,
  );
  return {
    usedBytes,
    remainingBytes,
    limitBytes: QUOTATION_STORAGE_LIMIT_BYTES,
    usedPercent: Math.min(
      100,
      (usedBytes / QUOTATION_STORAGE_LIMIT_BYTES) * 100,
    ),
    remainingPercent: Math.max(
      0,
      (remainingBytes / QUOTATION_STORAGE_LIMIT_BYTES) * 100,
    ),
    documentCount: Number(row?.document_count) || 0,
    pageCount: Number(row?.page_count) || 0,
    trashedBytes,
  };
}

export function quotationDocumentJson(row: QuotationDocumentRow) {
  const pageKeys = parseStoredStringList(row.page_keys_json);
  return {
    id: row.id,
    organization: row.organization,
    companyName: row.company_name,
    quoteAmount: row.quote_amount,
    quoteDate: row.quote_date,
    originalName: row.original_name,
    originalSize: Number(row.original_size) || 0,
    pageCount: Number(row.page_count) || pageKeys.length,
    totalSize: Number(row.total_size) || 0,
    createdByName: row.created_by_name,
    createdAt: row.created_at,
    originalUrl: `/api/quotation-documents?id=${row.id}&file=original`,
    downloadUrl: `/api/quotation-documents?id=${row.id}&file=original&download=1`,
    pageUrls: pageKeys.map(
      (_, index) =>
        `/api/quotation-documents?id=${row.id}&file=page&page=${index + 1}`,
    ),
  };
}
