export const VERCEL_SCHEMA_VERSION = "202607200001_sites_v94_parallel";

export const VERCEL_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS public.vercel_schema_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS is_sales smallint NOT NULL DEFAULT 0;

ALTER TABLE public.activities
  ADD COLUMN IF NOT EXISTS contact_role text NOT NULL DEFAULT '';

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'activities'
      AND column_name = 'follow_up_required'
      AND data_type = 'boolean'
  ) THEN
    ALTER TABLE public.activities
      ALTER COLUMN follow_up_required DROP DEFAULT;
    ALTER TABLE public.activities
      ALTER COLUMN follow_up_required TYPE smallint
      USING CASE WHEN follow_up_required THEN 1 ELSE 0 END;
    ALTER TABLE public.activities
      ALTER COLUMN follow_up_required SET DEFAULT 1;
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.ai_recommendations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id bigint NOT NULL UNIQUE
    REFERENCES public.activities(id) ON DELETE CASCADE,
  organization text NOT NULL,
  meeting_summary text NOT NULL DEFAULT '',
  interests_json text NOT NULL DEFAULT '[]',
  recommended_products_json text NOT NULL DEFAULT '[]',
  follow_up_questions_json text NOT NULL DEFAULT '[]',
  recommended_actions_json text NOT NULL DEFAULT '[]',
  applied_products_json text NOT NULL DEFAULT '[]',
  applied_questions_json text NOT NULL DEFAULT '[]',
  applied_actions_json text NOT NULL DEFAULT '[]',
  follow_up_date text,
  created_by bigint NOT NULL
    REFERENCES public.members(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.manager_alert_acknowledgements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE CASCADE,
  organization text NOT NULL,
  issue_signature text NOT NULL,
  snoozed_until text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (member_id, organization)
);

CREATE TABLE IF NOT EXISTS public.activity_review_acknowledgements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE CASCADE,
  activity_id bigint NOT NULL
    REFERENCES public.activities(id) ON DELETE CASCADE,
  issue_signature text NOT NULL,
  snoozed_until text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (member_id, activity_id)
);

CREATE TABLE IF NOT EXISTS public.activity_assignment_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id bigint NOT NULL
    REFERENCES public.activities(id) ON DELETE CASCADE,
  from_manager text NOT NULL DEFAULT '',
  to_member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE RESTRICT,
  to_manager text NOT NULL,
  changed_by_member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE RESTRICT,
  changed_by_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.api_credentials (
  id integer PRIMARY KEY CHECK (id = 1),
  encrypted_key text NOT NULL,
  iv text NOT NULL,
  key_last4 text NOT NULL,
  model text NOT NULL,
  updated_by bigint REFERENCES public.members(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS members_sales_idx
  ON public.members (status, is_sales, display_name);
CREATE INDEX IF NOT EXISTS activities_organization_date_idx
  ON public.activities (organization, activity_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS activities_date_idx
  ON public.activities (activity_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS activities_manager_created_idx
  ON public.activities (progress_manager, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ai_recommendations_org_idx
  ON public.ai_recommendations (organization, updated_at);
CREATE INDEX IF NOT EXISTS manager_alert_ack_snoozed_idx
  ON public.manager_alert_acknowledgements (member_id, snoozed_until);
CREATE INDEX IF NOT EXISTS activity_review_ack_snoozed_idx
  ON public.activity_review_acknowledgements (member_id, snoozed_until);
CREATE INDEX IF NOT EXISTS activity_assignment_history_activity_idx
  ON public.activity_assignment_history (activity_id, created_at);

DROP TRIGGER IF EXISTS ai_recommendations_touch_updated_at
  ON public.ai_recommendations;
CREATE TRIGGER ai_recommendations_touch_updated_at
BEFORE UPDATE ON public.ai_recommendations
FOR EACH ROW EXECUTE FUNCTION security.touch_updated_at();

DROP TRIGGER IF EXISTS manager_alert_ack_touch_updated_at
  ON public.manager_alert_acknowledgements;
CREATE TRIGGER manager_alert_ack_touch_updated_at
BEFORE UPDATE ON public.manager_alert_acknowledgements
FOR EACH ROW EXECUTE FUNCTION security.touch_updated_at();

DROP TRIGGER IF EXISTS activity_review_ack_touch_updated_at
  ON public.activity_review_acknowledgements;
CREATE TRIGGER activity_review_ack_touch_updated_at
BEFORE UPDATE ON public.activity_review_acknowledgements
FOR EACH ROW EXECUTE FUNCTION security.touch_updated_at();

ALTER TABLE public.vercel_schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manager_alert_acknowledgements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_review_acknowledgements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_assignment_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_credentials ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.vercel_schema_migrations
  FROM anon, authenticated;
REVOKE ALL ON public.ai_recommendations
  FROM anon, authenticated;
REVOKE ALL ON public.manager_alert_acknowledgements
  FROM anon, authenticated;
REVOKE ALL ON public.activity_review_acknowledgements
  FROM anon, authenticated;
REVOKE ALL ON public.activity_assignment_history
  FROM anon, authenticated;
REVOKE ALL ON public.api_credentials
  FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public
  FROM anon, authenticated;

UPDATE public.activities
SET execution_type = '직영', consortium_company = ''
WHERE execution_type IS NULL
   OR execution_type = ''
   OR execution_type = '미정';

INSERT INTO public.vercel_schema_migrations (version)
VALUES ('${VERCEL_SCHEMA_VERSION}')
ON CONFLICT (version) DO NOTHING;
`;
