export const VERCEL_SCHEMA_VERSION = "202608060001_sites_v399";

export const VERCEL_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS public.vercel_schema_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS is_sales smallint NOT NULL DEFAULT 0;
ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS current_view text NOT NULL DEFAULT '';
ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS auth_user_id uuid;
CREATE UNIQUE INDEX IF NOT EXISTS members_auth_user_id_idx
  ON public.members (auth_user_id)
  WHERE auth_user_id IS NOT NULL;

ALTER TABLE public.activities
  ADD COLUMN IF NOT EXISTS budgets_json text NOT NULL DEFAULT '[]';

CREATE TABLE IF NOT EXISTS public.joint_projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  sponsor_organization text NOT NULL,
  campaign_id bigint,
  budget_group_id bigint,
  budget_type text NOT NULL DEFAULT '',
  project_year integer NOT NULL DEFAULT 0,
  joint_round integer NOT NULL DEFAULT 1,
  notes text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'active',
  created_by bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS joint_projects_campaign_idx
  ON public.joint_projects (campaign_id, status);
CREATE INDEX IF NOT EXISTS joint_projects_sponsor_idx
  ON public.joint_projects (sponsor_organization, status);
CREATE INDEX IF NOT EXISTS joint_projects_budget_period_idx
  ON public.joint_projects (budget_group_id, project_year, joint_round, status);

CREATE TABLE IF NOT EXISTS public.joint_project_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL,
  organization text NOT NULL,
  institution_key text NOT NULL DEFAULT '',
  business_round integer NOT NULL DEFAULT 1,
  role text NOT NULL DEFAULT 'site',
  activity_id bigint,
  campaign_target_id bigint,
  budget_amount bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS joint_project_members_project_business_idx
  ON public.joint_project_members (project_id, organization, business_round);
CREATE INDEX IF NOT EXISTS joint_project_members_business_idx
  ON public.joint_project_members (organization, business_round, project_id);
CREATE INDEX IF NOT EXISTS joint_project_members_institution_idx
  ON public.joint_project_members (institution_key, business_round, project_id);
CREATE INDEX IF NOT EXISTS joint_project_members_campaign_target_idx
  ON public.joint_project_members (campaign_target_id);

CREATE TABLE IF NOT EXISTS public.joint_project_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL,
  action text NOT NULL,
  detail_json text NOT NULL DEFAULT '{}',
  changed_by bigint NOT NULL,
  changed_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS joint_project_events_project_idx
  ON public.joint_project_events (project_id);

CREATE TABLE IF NOT EXISTS public.inventory_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  specification text NOT NULL DEFAULT '',
  unit text NOT NULL DEFAULT '대',
  current_stock bigint NOT NULL DEFAULT 0,
  low_stock_threshold bigint NOT NULL DEFAULT 1,
  is_active smallint NOT NULL DEFAULT 1,
  created_by bigint,
  created_by_name text NOT NULL DEFAULT '',
  updated_by bigint,
  updated_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS inventory_products_name_idx
  ON public.inventory_products (name);

CREATE TABLE IF NOT EXISTS public.inventory_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL,
  transaction_type text NOT NULL,
  quantity_delta bigint NOT NULL,
  resulting_stock bigint NOT NULL,
  reference text NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  transaction_date text NOT NULL,
  created_by bigint,
  created_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inventory_transactions_product_date_idx
  ON public.inventory_transactions (product_id, transaction_date, id);
CREATE INDEX IF NOT EXISTS inventory_transactions_date_idx
  ON public.inventory_transactions (transaction_date, id);

INSERT INTO public.inventory_products
  (name, specification, unit, low_stock_threshold)
VALUES
  ('3D모션', '3D 모션 스포츠 장비', '대', 1),
  ('터치테이블', '터치형 테이블 장비', '대', 1)
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.organization_schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization text NOT NULL,
  business_round integer NOT NULL DEFAULT 1,
  label text NOT NULL,
  scheduled_date text NOT NULL,
  start_time text NOT NULL DEFAULT '',
  end_time text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT 'general',
  stage text NOT NULL DEFAULT '',
  end_date text NOT NULL DEFAULT '',
  vendor_name text NOT NULL DEFAULT '',
  details text NOT NULL DEFAULT '',
  completed smallint NOT NULL DEFAULT 0,
  source_activity_id bigint,
  assignee_member_id bigint,
  assignee_name text NOT NULL DEFAULT '',
  google_event_id text NOT NULL DEFAULT '',
  google_event_etag text NOT NULL DEFAULT '',
  google_origin smallint NOT NULL DEFAULT 0,
  sync_status text NOT NULL DEFAULT 'pending',
  sync_operation text NOT NULL DEFAULT 'upsert',
  sync_error text NOT NULL DEFAULT '',
  sync_attempts integer NOT NULL DEFAULT 0,
  last_synced_at text NOT NULL DEFAULT '',
  google_updated_at text NOT NULL DEFAULT '',
  deleted_at text NOT NULL DEFAULT '',
  created_by bigint,
  created_by_name text NOT NULL DEFAULT '',
  updated_by bigint,
  updated_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS organization_schedules_scope_date_idx
  ON public.organization_schedules
  (organization, business_round, completed, scheduled_date, id);
CREATE INDEX IF NOT EXISTS organization_schedules_sync_idx
  ON public.organization_schedules
  (sync_status, sync_operation, updated_at, id);
CREATE INDEX IF NOT EXISTS organization_schedules_assignee_idx
  ON public.organization_schedules
  (assignee_member_id, completed, scheduled_date);
CREATE UNIQUE INDEX IF NOT EXISTS organization_schedules_google_event_idx
  ON public.organization_schedules (google_event_id)
  WHERE google_event_id <> '';

CREATE TABLE IF NOT EXISTS public.construction_schedule_projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization text NOT NULL,
  business_round integer NOT NULL DEFAULT 1,
  work_summary text NOT NULL DEFAULT '',
  work_summary_mode text NOT NULL DEFAULT 'auto',
  completed smallint NOT NULL DEFAULT 0,
  hidden_at text NOT NULL DEFAULT '',
  created_by bigint,
  created_by_name text NOT NULL DEFAULT '',
  updated_by bigint,
  updated_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS construction_schedule_projects_scope_idx
  ON public.construction_schedule_projects (organization, business_round);

CREATE TABLE IF NOT EXISTS public.authored_quotations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_number text NOT NULL UNIQUE,
  organization text NOT NULL,
  business_round integer NOT NULL DEFAULT 1,
  project_title text NOT NULL DEFAULT '',
  quote_date text NOT NULL,
  valid_until text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'draft',
  execution_type text NOT NULL DEFAULT '직영',
  consortium_company text NOT NULL DEFAULT '',
  consortium_rate text NOT NULL DEFAULT '0',
  discount_amount bigint NOT NULL DEFAULT 0,
  extra_amount bigint NOT NULL DEFAULT 0,
  subtotal_amount bigint NOT NULL DEFAULT 0,
  supply_amount bigint NOT NULL DEFAULT 0,
  tax_amount bigint NOT NULL DEFAULT 0,
  total_amount bigint NOT NULL DEFAULT 0,
  expected_earning bigint NOT NULL DEFAULT 0,
  consortium_payment bigint NOT NULL DEFAULT 0,
  margin_amount bigint NOT NULL DEFAULT 0,
  margin_rate text NOT NULL DEFAULT '0',
  include_stamp smallint NOT NULL DEFAULT 0,
  memo text NOT NULL DEFAULT '',
  items_json text NOT NULL DEFAULT '[]',
  created_by bigint NOT NULL,
  created_by_name text NOT NULL DEFAULT '',
  updated_by bigint NOT NULL,
  updated_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS authored_quotations_org_date_idx
  ON public.authored_quotations
  (organization, business_round, quote_date, id);

ALTER TABLE public.activities
  ADD COLUMN IF NOT EXISTS contact_role text NOT NULL DEFAULT '';

ALTER TABLE public.activities
  ADD COLUMN IF NOT EXISTS business_round integer NOT NULL DEFAULT 1;

ALTER TABLE public.equipment_projects
  ADD COLUMN IF NOT EXISTS business_round integer NOT NULL DEFAULT 1;
ALTER TABLE public.equipment_projects
  ADD COLUMN IF NOT EXISTS activity_id bigint;
ALTER TABLE public.equipment_projects
  ADD COLUMN IF NOT EXISTS construction_amount bigint;
ALTER TABLE public.equipment_projects
  ADD COLUMN IF NOT EXISTS actual_construction_cost bigint;

ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS catalog_item_id text NOT NULL DEFAULT '';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS catalog_unit_price bigint;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS catalog_note text NOT NULL DEFAULT '';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS execution_type text NOT NULL DEFAULT '직영';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS commission_input_type text NOT NULL DEFAULT 'rate';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS commission_rate double precision;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS procurement_fee_rate double precision;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS consortium_commission_rate double precision;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS consortium_payment_amount bigint;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS protection_status text NOT NULL DEFAULT '신청 필요';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS protection_completed_at text;

-- The original standby database used fixed enum-like checks from the first
-- release. The main Sites database stores these fields as text and now uses
-- additional values such as 협력사 수주 and 해당 없음. Keeping the legacy
-- checks would reject an otherwise valid full backup during standby sync.
ALTER TABLE public.activities
  DROP CONSTRAINT IF EXISTS activities_award_status_check;
ALTER TABLE public.activities
  DROP CONSTRAINT IF EXISTS activities_execution_type_check;
ALTER TABLE public.activities
  DROP CONSTRAINT IF EXISTS activities_award_stage_check;

DO $$
DECLARE
  old_constraint text;
BEGIN
  SELECT tc.constraint_name
  INTO old_constraint
  FROM information_schema.table_constraints tc
  WHERE tc.table_schema = 'public'
    AND tc.table_name = 'equipment_projects'
    AND tc.constraint_type = 'UNIQUE'
    AND (
      SELECT array_agg(kcu.column_name::text ORDER BY kcu.column_name::text)
      FROM information_schema.key_column_usage kcu
      WHERE kcu.constraint_schema = tc.constraint_schema
        AND kcu.constraint_name = tc.constraint_name
    ) = ARRAY['name', 'organization']::text[]
  LIMIT 1;

  IF old_constraint IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.equipment_projects DROP CONSTRAINT %I',
      old_constraint
    );
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS equipment_projects_org_round_name_idx
  ON public.equipment_projects (organization, business_round, name);
CREATE INDEX IF NOT EXISTS equipment_projects_activity_idx
  ON public.equipment_projects (activity_id, updated_at);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'activities'
      AND column_name = 'follow_up_required'
      AND data_type = 'boolean'
  ) THEN
    ALTER TABLE public.activities
      ALTER COLUMN follow_up_required DROP DEFAULT;
    ALTER TABLE public.activities
      ALTER COLUMN follow_up_required TYPE smallint
      USING CASE WHEN follow_up_required THEN 1 ELSE 0 END;
    ALTER TABLE public.activities
      ALTER COLUMN follow_up_required SET DEFAULT 1;
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.ai_recommendations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id bigint NOT NULL UNIQUE
    REFERENCES public.activities(id) ON DELETE CASCADE,
  organization text NOT NULL,
  meeting_summary text NOT NULL DEFAULT '',
  interests_json text NOT NULL DEFAULT '[]',
  recommended_products_json text NOT NULL DEFAULT '[]',
  follow_up_questions_json text NOT NULL DEFAULT '[]',
  recommended_actions_json text NOT NULL DEFAULT '[]',
  applied_products_json text NOT NULL DEFAULT '[]',
  applied_questions_json text NOT NULL DEFAULT '[]',
  applied_actions_json text NOT NULL DEFAULT '[]',
  follow_up_date text,
  created_by bigint NOT NULL
    REFERENCES public.members(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.manager_alert_acknowledgements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE CASCADE,
  organization text NOT NULL,
  issue_signature text NOT NULL,
  snoozed_until text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (member_id, organization)
);

CREATE TABLE IF NOT EXISTS public.activity_review_acknowledgements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE CASCADE,
  activity_id bigint NOT NULL
    REFERENCES public.activities(id) ON DELETE CASCADE,
  issue_signature text NOT NULL,
  snoozed_until text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (member_id, activity_id)
);

CREATE TABLE IF NOT EXISTS public.activity_assignment_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id bigint NOT NULL
    REFERENCES public.activities(id) ON DELETE CASCADE,
  from_manager text NOT NULL DEFAULT '',
  to_member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE RESTRICT,
  to_manager text NOT NULL,
  changed_by_member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE RESTRICT,
  changed_by_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.api_credentials (
  id integer PRIMARY KEY CHECK (id = 1),
  encrypted_key text NOT NULL,
  iv text NOT NULL,
  key_last4 text NOT NULL,
  model text NOT NULL,
  updated_by bigint REFERENCES public.members(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.replication_sync_state (
  id integer PRIMARY KEY CHECK (id = 1),
  source_origin text NOT NULL DEFAULT '',
  source_created_at timestamptz,
  source_checksum text NOT NULL DEFAULT '',
  source_counts_json text NOT NULL DEFAULT '{}',
  status text NOT NULL DEFAULT 'idle'
    CHECK (status IN ('idle', 'syncing', 'succeeded', 'failed')),
  last_attempt_at timestamptz,
  last_success_at timestamptz,
  duration_ms integer,
  error_message text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS members_sales_idx
  ON public.members (status, is_sales, display_name);
CREATE INDEX IF NOT EXISTS activities_organization_date_idx
  ON public.activities (organization, activity_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS activities_date_idx
  ON public.activities (activity_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS activities_manager_created_idx
  ON public.activities (progress_manager, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ai_recommendations_org_idx
  ON public.ai_recommendations (organization, updated_at);
CREATE INDEX IF NOT EXISTS manager_alert_ack_snoozed_idx
  ON public.manager_alert_acknowledgements (member_id, snoozed_until);
CREATE INDEX IF NOT EXISTS activity_review_ack_snoozed_idx
  ON public.activity_review_acknowledgements (member_id, snoozed_until);
CREATE INDEX IF NOT EXISTS activity_assignment_history_activity_idx
  ON public.activity_assignment_history (activity_id, created_at);

DROP TRIGGER IF EXISTS ai_recommendations_touch_updated_at
  ON public.ai_recommendations;
CREATE TRIGGER ai_recommendations_touch_updated_at
BEFORE UPDATE ON public.ai_recommendations
FOR EACH ROW EXECUTE FUNCTION security.touch_updated_at();

DROP TRIGGER IF EXISTS manager_alert_ack_touch_updated_at
  ON public.manager_alert_acknowledgements;
CREATE TRIGGER manager_alert_ack_touch_updated_at
BEFORE UPDATE ON public.manager_alert_acknowledgements
FOR EACH ROW EXECUTE FUNCTION security.touch_updated_at();

DROP TRIGGER IF EXISTS activity_review_ack_touch_updated_at
  ON public.activity_review_acknowledgements;
CREATE TRIGGER activity_review_ack_touch_updated_at
BEFORE UPDATE ON public.activity_review_acknowledgements
FOR EACH ROW EXECUTE FUNCTION security.touch_updated_at();

ALTER TABLE public.vercel_schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manager_alert_acknowledgements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_review_acknowledgements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_assignment_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.replication_sync_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.joint_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.joint_project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.joint_project_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.construction_schedule_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.authored_quotations ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.vercel_schema_migrations
  FROM anon, authenticated;
REVOKE ALL ON public.ai_recommendations
  FROM anon, authenticated;
REVOKE ALL ON public.manager_alert_acknowledgements
  FROM anon, authenticated;
REVOKE ALL ON public.activity_review_acknowledgements
  FROM anon, authenticated;
REVOKE ALL ON public.activity_assignment_history
  FROM anon, authenticated;
REVOKE ALL ON public.api_credentials
  FROM anon, authenticated;
REVOKE ALL ON public.replication_sync_state
  FROM anon, authenticated;
REVOKE ALL ON public.joint_projects
  FROM anon, authenticated;
REVOKE ALL ON public.joint_project_members
  FROM anon, authenticated;
REVOKE ALL ON public.joint_project_events
  FROM anon, authenticated;
REVOKE ALL ON public.inventory_products
  FROM anon, authenticated;
REVOKE ALL ON public.inventory_transactions
  FROM anon, authenticated;
REVOKE ALL ON public.organization_schedules
  FROM anon, authenticated;
REVOKE ALL ON public.construction_schedule_projects
  FROM anon, authenticated;
REVOKE ALL ON public.authored_quotations
  FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public
  FROM anon, authenticated;

UPDATE public.activities
SET execution_type = '직영', consortium_company = ''
WHERE execution_type IS NULL
   OR execution_type = ''
   OR execution_type = '미정';

INSERT INTO public.vercel_schema_migrations (version)
VALUES ('${VERCEL_SCHEMA_VERSION}')
ON CONFLICT (version) DO NOTHING;
`;
