export const VERCEL_SCHEMA_VERSION =
  "202608070002_complex_projects_page_loading_performance";

export const VERCEL_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS public.vercel_schema_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS is_sales smallint NOT NULL DEFAULT 0;
ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS current_view text NOT NULL DEFAULT '';
ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS auth_user_id uuid;
CREATE UNIQUE INDEX IF NOT EXISTS members_auth_user_id_idx
  ON public.members (auth_user_id)
  WHERE auth_user_id IS NOT NULL;

ALTER TABLE public.activities
  ADD COLUMN IF NOT EXISTS budgets_json text NOT NULL DEFAULT '[]';
ALTER TABLE public.activities
  ADD COLUMN IF NOT EXISTS award_stage_manual smallint NOT NULL DEFAULT 0;

ALTER TABLE public.organization_schedules
  ADD COLUMN IF NOT EXISTS complex_delivery_id bigint;
CREATE UNIQUE INDEX IF NOT EXISTS organization_schedules_complex_delivery_idx
  ON public.organization_schedules (complex_delivery_id)
  WHERE complex_delivery_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.complex_projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization text NOT NULL,
  business_round integer NOT NULL DEFAULT 1,
  name text NOT NULL,
  status text NOT NULL DEFAULT '준비',
  total_budget bigint,
  manager_name text NOT NULL DEFAULT '',
  notes text NOT NULL DEFAULT '',
  active smallint NOT NULL DEFAULT 1,
  created_by bigint NOT NULL,
  created_by_name text NOT NULL DEFAULT '',
  updated_by bigint,
  updated_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization, business_round)
);
CREATE INDEX IF NOT EXISTS complex_projects_active_idx
  ON public.complex_projects (active, status, updated_at, id);

CREATE TABLE IF NOT EXISTS public.complex_project_budget_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complex_project_id bigint NOT NULL,
  equipment_project_id bigint NOT NULL,
  allocated_amount bigint,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (complex_project_id, equipment_project_id)
);
CREATE INDEX IF NOT EXISTS complex_project_budget_links_project_idx
  ON public.complex_project_budget_links (complex_project_id, sort_order, id);

CREATE TABLE IF NOT EXISTS public.complex_project_zones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complex_project_id bigint NOT NULL,
  building text NOT NULL DEFAULT '',
  floor text NOT NULL DEFAULT '',
  room text NOT NULL DEFAULT '',
  name text NOT NULL,
  notes text NOT NULL DEFAULT '',
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS complex_project_zones_project_idx
  ON public.complex_project_zones (complex_project_id, sort_order, id);

CREATE TABLE IF NOT EXISTS public.complex_project_item_details (
  equipment_item_id bigint PRIMARY KEY,
  complex_project_id bigint NOT NULL,
  zone_id bigint,
  item_category text NOT NULL DEFAULT '기자재',
  procurement_method text NOT NULL DEFAULT '',
  procurement_identifier text NOT NULL DEFAULT '',
  delivery_location text NOT NULL DEFAULT '',
  updated_by bigint,
  updated_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS complex_project_item_details_project_idx
  ON public.complex_project_item_details (complex_project_id, zone_id, equipment_item_id);

CREATE TABLE IF NOT EXISTS public.complex_project_deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complex_project_id bigint NOT NULL,
  equipment_item_id bigint NOT NULL,
  schedule_id bigint,
  kind text NOT NULL DEFAULT '납품',
  planned_qty integer NOT NULL DEFAULT 0,
  completed_qty integer NOT NULL DEFAULT 0,
  start_date text NOT NULL DEFAULT '',
  end_date text NOT NULL DEFAULT '',
  vendor_name text NOT NULL DEFAULT '',
  location text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT '일정 미정',
  notes text NOT NULL DEFAULT '',
  created_by bigint,
  created_by_name text NOT NULL DEFAULT '',
  updated_by bigint,
  updated_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS complex_project_deliveries_project_idx
  ON public.complex_project_deliveries (complex_project_id, start_date, id);
CREATE INDEX IF NOT EXISTS complex_project_deliveries_item_idx
  ON public.complex_project_deliveries (equipment_item_id, status, id);

CREATE TABLE IF NOT EXISTS public.complex_project_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complex_project_id bigint NOT NULL,
  action text NOT NULL,
  detail_json text NOT NULL DEFAULT '{}',
  changed_by bigint NOT NULL,
  changed_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS complex_project_events_project_idx
  ON public.complex_project_events (complex_project_id, created_at, id);

ALTER TABLE public.quotation_documents
  ADD COLUMN IF NOT EXISTS business_round integer NOT NULL DEFAULT 1;

ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS budget_type text NOT NULL DEFAULT '';
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS budget_group_id bigint;
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS budget_match_status text NOT NULL DEFAULT 'unclassified';
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS budget_match_method text NOT NULL DEFAULT 'legacy';
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS budget_request_id text;
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS budget_kind text NOT NULL DEFAULT 'unclassified';
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS budget_amount_mode text NOT NULL DEFAULT 'manual';
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS default_budget_amount bigint;
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS source_file_name text NOT NULL DEFAULT '';
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS import_source text NOT NULL DEFAULT '';

ALTER TABLE public.sales_campaign_targets
  ADD COLUMN IF NOT EXISTS budget_amount bigint;
ALTER TABLE public.sales_campaign_targets
  ADD COLUMN IF NOT EXISTS school_level text NOT NULL DEFAULT '';
ALTER TABLE public.sales_campaign_targets
  ADD COLUMN IF NOT EXISTS supply_items text NOT NULL DEFAULT '';
ALTER TABLE public.sales_campaign_targets
  ADD COLUMN IF NOT EXISTS review_note text NOT NULL DEFAULT '';
ALTER TABLE public.sales_campaign_targets
  ADD COLUMN IF NOT EXISTS created_activity smallint NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS public.joint_projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  sponsor_organization text NOT NULL,
  campaign_id bigint,
  budget_group_id bigint,
  budget_type text NOT NULL DEFAULT '',
  project_year integer NOT NULL DEFAULT 0,
  joint_round integer NOT NULL DEFAULT 1,
  notes text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'active',
  created_by bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS joint_projects_campaign_idx
  ON public.joint_projects (campaign_id, status);
CREATE INDEX IF NOT EXISTS joint_projects_sponsor_idx
  ON public.joint_projects (sponsor_organization, status);
CREATE INDEX IF NOT EXISTS joint_projects_budget_period_idx
  ON public.joint_projects (budget_group_id, project_year, joint_round, status);

CREATE TABLE IF NOT EXISTS public.joint_project_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL,
  organization text NOT NULL,
  institution_key text NOT NULL DEFAULT '',
  business_round integer NOT NULL DEFAULT 1,
  role text NOT NULL DEFAULT 'site',
  activity_id bigint,
  campaign_target_id bigint,
  budget_amount bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.joint_project_members
  ADD COLUMN IF NOT EXISTS institution_key text NOT NULL DEFAULT '';
ALTER TABLE public.joint_project_members
  ADD COLUMN IF NOT EXISTS business_round integer NOT NULL DEFAULT 1;
ALTER TABLE public.joint_project_members
  ADD COLUMN IF NOT EXISTS campaign_target_id bigint;
CREATE UNIQUE INDEX IF NOT EXISTS joint_project_members_project_business_idx
  ON public.joint_project_members (project_id, organization, business_round);
CREATE INDEX IF NOT EXISTS joint_project_members_business_idx
  ON public.joint_project_members (organization, business_round, project_id);
CREATE INDEX IF NOT EXISTS joint_project_members_institution_idx
  ON public.joint_project_members (institution_key, business_round, project_id);
CREATE INDEX IF NOT EXISTS joint_project_members_campaign_target_idx
  ON public.joint_project_members (campaign_target_id);

CREATE TABLE IF NOT EXISTS public.joint_project_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL,
  action text NOT NULL,
  detail_json text NOT NULL DEFAULT '{}',
  changed_by bigint NOT NULL,
  changed_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS joint_project_events_project_idx
  ON public.joint_project_events (project_id);

CREATE TABLE IF NOT EXISTS public.inventory_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  specification text NOT NULL DEFAULT '',
  unit text NOT NULL DEFAULT '대',
  current_stock bigint NOT NULL DEFAULT 0,
  low_stock_threshold bigint NOT NULL DEFAULT 1,
  is_active smallint NOT NULL DEFAULT 1,
  created_by bigint,
  created_by_name text NOT NULL DEFAULT '',
  updated_by bigint,
  updated_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS inventory_products_name_idx
  ON public.inventory_products (name);

CREATE TABLE IF NOT EXISTS public.inventory_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL,
  transaction_type text NOT NULL,
  quantity_delta bigint NOT NULL,
  resulting_stock bigint NOT NULL,
  reference text NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  transaction_date text NOT NULL,
  created_by bigint,
  created_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inventory_transactions_product_date_idx
  ON public.inventory_transactions (product_id, transaction_date, id);
CREATE INDEX IF NOT EXISTS inventory_transactions_date_idx
  ON public.inventory_transactions (transaction_date, id);

INSERT INTO public.inventory_products
  (name, specification, unit, low_stock_threshold)
VALUES
  ('3D모션', '3D 모션 스포츠 장비', '대', 1),
  ('터치테이블', '터치형 테이블 장비', '대', 1)
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.organization_schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization text NOT NULL,
  business_round integer NOT NULL DEFAULT 1,
  label text NOT NULL,
  scheduled_date text NOT NULL,
  start_time text NOT NULL DEFAULT '',
  end_time text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT 'general',
  stage text NOT NULL DEFAULT '',
  end_date text NOT NULL DEFAULT '',
  vendor_name text NOT NULL DEFAULT '',
  details text NOT NULL DEFAULT '',
  completed smallint NOT NULL DEFAULT 0,
  source_activity_id bigint,
  assignee_member_id bigint,
  assignee_name text NOT NULL DEFAULT '',
  google_event_id text NOT NULL DEFAULT '',
  google_event_etag text NOT NULL DEFAULT '',
  google_origin smallint NOT NULL DEFAULT 0,
  sync_status text NOT NULL DEFAULT 'pending',
  sync_operation text NOT NULL DEFAULT 'upsert',
  sync_error text NOT NULL DEFAULT '',
  sync_attempts integer NOT NULL DEFAULT 0,
  last_synced_at text NOT NULL DEFAULT '',
  google_updated_at text NOT NULL DEFAULT '',
  deleted_at text NOT NULL DEFAULT '',
  created_by bigint,
  created_by_name text NOT NULL DEFAULT '',
  updated_by bigint,
  updated_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.organization_schedules
  ADD COLUMN IF NOT EXISTS business_round integer NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS organization_schedules_scope_date_idx
  ON public.organization_schedules
  (organization, business_round, completed, scheduled_date, id);
CREATE INDEX IF NOT EXISTS organization_schedules_sync_idx
  ON public.organization_schedules
  (sync_status, sync_operation, updated_at, id);
CREATE INDEX IF NOT EXISTS organization_schedules_assignee_idx
  ON public.organization_schedules
  (assignee_member_id, completed, scheduled_date);
CREATE UNIQUE INDEX IF NOT EXISTS organization_schedules_google_event_idx
  ON public.organization_schedules (google_event_id)
  WHERE google_event_id <> '';

CREATE TABLE IF NOT EXISTS public.construction_schedule_projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization text NOT NULL,
  business_round integer NOT NULL DEFAULT 1,
  work_summary text NOT NULL DEFAULT '',
  work_summary_mode text NOT NULL DEFAULT 'auto',
  completed smallint NOT NULL DEFAULT 0,
  hidden_at text NOT NULL DEFAULT '',
  created_by bigint,
  created_by_name text NOT NULL DEFAULT '',
  updated_by bigint,
  updated_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.construction_schedule_projects
  ADD COLUMN IF NOT EXISTS business_round integer NOT NULL DEFAULT 1;
ALTER TABLE public.construction_schedule_projects
  ADD COLUMN IF NOT EXISTS work_summary_mode text NOT NULL DEFAULT 'auto';
ALTER TABLE public.construction_schedule_projects
  ADD COLUMN IF NOT EXISTS hidden_at text NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS construction_schedule_projects_scope_idx
  ON public.construction_schedule_projects (organization, business_round);

ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS selection_date text NOT NULL DEFAULT '';
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS import_status text NOT NULL DEFAULT 'complete';
ALTER TABLE public.sales_campaigns
  ADD COLUMN IF NOT EXISTS expected_target_count integer NOT NULL DEFAULT 0;
ALTER TABLE public.sales_campaign_targets
  ADD COLUMN IF NOT EXISTS business_round integer NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS public.authored_quotations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_number text NOT NULL UNIQUE,
  organization text NOT NULL,
  business_round integer NOT NULL DEFAULT 1,
  project_title text NOT NULL DEFAULT '',
  quote_date text NOT NULL,
  valid_until text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'draft',
  execution_type text NOT NULL DEFAULT '직영',
  consortium_company text NOT NULL DEFAULT '',
  consortium_rate text NOT NULL DEFAULT '0',
  discount_amount bigint NOT NULL DEFAULT 0,
  extra_amount bigint NOT NULL DEFAULT 0,
  subtotal_amount bigint NOT NULL DEFAULT 0,
  supply_amount bigint NOT NULL DEFAULT 0,
  tax_amount bigint NOT NULL DEFAULT 0,
  total_amount bigint NOT NULL DEFAULT 0,
  expected_earning bigint NOT NULL DEFAULT 0,
  consortium_payment bigint NOT NULL DEFAULT 0,
  margin_amount bigint NOT NULL DEFAULT 0,
  margin_rate text NOT NULL DEFAULT '0',
  include_stamp smallint NOT NULL DEFAULT 0,
  memo text NOT NULL DEFAULT '',
  items_json text NOT NULL DEFAULT '[]',
  created_by bigint NOT NULL,
  created_by_name text NOT NULL DEFAULT '',
  updated_by bigint NOT NULL,
  updated_by_name text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.authored_quotations
  ADD COLUMN IF NOT EXISTS business_round integer NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS authored_quotations_org_date_idx
  ON public.authored_quotations
  (organization, business_round, quote_date, id);

ALTER TABLE public.activities
  ADD COLUMN IF NOT EXISTS contact_role text NOT NULL DEFAULT '';

ALTER TABLE public.activities
  ADD COLUMN IF NOT EXISTS business_round integer NOT NULL DEFAULT 1;

ALTER TABLE public.equipment_projects
  ADD COLUMN IF NOT EXISTS business_round integer NOT NULL DEFAULT 1;
ALTER TABLE public.equipment_projects
  ADD COLUMN IF NOT EXISTS activity_id bigint;
ALTER TABLE public.equipment_projects
  ADD COLUMN IF NOT EXISTS construction_amount bigint;
ALTER TABLE public.equipment_projects
  ADD COLUMN IF NOT EXISTS actual_construction_cost bigint;

ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS catalog_item_id text NOT NULL DEFAULT '';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS catalog_unit_price bigint;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS catalog_note text NOT NULL DEFAULT '';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS execution_type text NOT NULL DEFAULT '직영';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS commission_input_type text NOT NULL DEFAULT 'rate';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS commission_rate double precision;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS procurement_fee_rate double precision;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS consortium_commission_rate double precision;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS consortium_payment_amount bigint;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS protection_status text NOT NULL DEFAULT '신청 필요';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS protection_completed_at text;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS supplier_vendor_id bigint;
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS supplier_vendor_name text NOT NULL DEFAULT '';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS supply_type text NOT NULL DEFAULT 'partner';
ALTER TABLE public.equipment_items
  ADD COLUMN IF NOT EXISTS margin_rate double precision;

-- The original standby database used fixed enum-like checks from the first
-- release. The main Sites database stores these fields as text and now uses
-- additional values such as 협력사 수주 and 해당 없음. Keeping the legacy
-- checks would reject an otherwise valid full backup during standby sync.
ALTER TABLE public.activities
  DROP CONSTRAINT IF EXISTS activities_award_status_check;
ALTER TABLE public.activities
  DROP CONSTRAINT IF EXISTS activities_execution_type_check;
ALTER TABLE public.activities
  DROP CONSTRAINT IF EXISTS activities_award_stage_check;

DO $$
DECLARE
  old_constraint text;
BEGIN
  SELECT tc.constraint_name
  INTO old_constraint
  FROM information_schema.table_constraints tc
  WHERE tc.table_schema = 'public'
    AND tc.table_name = 'equipment_projects'
    AND tc.constraint_type = 'UNIQUE'
    AND (
      SELECT array_agg(kcu.column_name::text ORDER BY kcu.column_name::text)
      FROM information_schema.key_column_usage kcu
      WHERE kcu.constraint_schema = tc.constraint_schema
        AND kcu.constraint_name = tc.constraint_name
    ) = ARRAY['name', 'organization']::text[]
  LIMIT 1;

  IF old_constraint IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.equipment_projects DROP CONSTRAINT %I',
      old_constraint
    );
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS equipment_projects_org_round_name_idx
  ON public.equipment_projects (organization, business_round, name);
CREATE INDEX IF NOT EXISTS equipment_projects_activity_idx
  ON public.equipment_projects (activity_id, updated_at);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'activities'
      AND column_name = 'follow_up_required'
      AND data_type = 'boolean'
  ) THEN
    ALTER TABLE public.activities
      ALTER COLUMN follow_up_required DROP DEFAULT;
    ALTER TABLE public.activities
      ALTER COLUMN follow_up_required TYPE smallint
      USING CASE WHEN follow_up_required THEN 1 ELSE 0 END;
    ALTER TABLE public.activities
      ALTER COLUMN follow_up_required SET DEFAULT 1;
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.ai_recommendations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id bigint NOT NULL UNIQUE
    REFERENCES public.activities(id) ON DELETE CASCADE,
  organization text NOT NULL,
  meeting_summary text NOT NULL DEFAULT '',
  interests_json text NOT NULL DEFAULT '[]',
  recommended_products_json text NOT NULL DEFAULT '[]',
  follow_up_questions_json text NOT NULL DEFAULT '[]',
  recommended_actions_json text NOT NULL DEFAULT '[]',
  applied_products_json text NOT NULL DEFAULT '[]',
  applied_questions_json text NOT NULL DEFAULT '[]',
  applied_actions_json text NOT NULL DEFAULT '[]',
  follow_up_date text,
  created_by bigint NOT NULL
    REFERENCES public.members(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.manager_alert_acknowledgements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE CASCADE,
  organization text NOT NULL,
  issue_signature text NOT NULL,
  snoozed_until text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (member_id, organization)
);
ALTER TABLE public.manager_alert_acknowledgements
  ADD COLUMN IF NOT EXISTS hidden_at text;

CREATE TABLE IF NOT EXISTS public.activity_review_acknowledgements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE CASCADE,
  activity_id bigint NOT NULL
    REFERENCES public.activities(id) ON DELETE CASCADE,
  issue_signature text NOT NULL,
  snoozed_until text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (member_id, activity_id)
);

CREATE TABLE IF NOT EXISTS public.activity_assignment_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id bigint NOT NULL
    REFERENCES public.activities(id) ON DELETE CASCADE,
  from_manager text NOT NULL DEFAULT '',
  to_member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE RESTRICT,
  to_manager text NOT NULL,
  changed_by_member_id bigint NOT NULL
    REFERENCES public.members(id) ON DELETE RESTRICT,
  changed_by_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.activity_change_batches (
  id text PRIMARY KEY,
  scope text NOT NULL DEFAULT 'awards',
  operation_label text NOT NULL DEFAULT '',
  operation_total bigint NOT NULL DEFAULT 0,
  requested_fields_json text NOT NULL DEFAULT '[]',
  actor_member_id bigint NOT NULL,
  actor_name text NOT NULL DEFAULT '',
  item_count integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'in_progress',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at text,
  undone_at text,
  undone_by_member_id bigint,
  undone_by_name text NOT NULL DEFAULT '',
  undo_result_json text NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS public.activity_change_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id text NOT NULL,
  activity_id bigint NOT NULL,
  organization text NOT NULL DEFAULT '',
  requested_fields_json text NOT NULL DEFAULT '[]',
  changed_fields_json text NOT NULL DEFAULT '[]',
  before_json text NOT NULL DEFAULT '{}',
  after_json text NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  undone_at text,
  undone_by_member_id bigint,
  undone_by_name text NOT NULL DEFAULT '',
  undo_status text NOT NULL DEFAULT 'pending',
  undo_result_json text NOT NULL DEFAULT '{}',
  UNIQUE (batch_id, activity_id)
);

CREATE TABLE IF NOT EXISTS public.data_control_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  subject text NOT NULL DEFAULT '',
  item_count integer NOT NULL DEFAULT 0,
  archive_ids_json text NOT NULL DEFAULT '[]',
  actor_member_id bigint NOT NULL,
  actor_name text NOT NULL DEFAULT '',
  details_json text NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.organization_school_links (
  link_key text PRIMARY KEY,
  organization text NOT NULL,
  organization_key text NOT NULL,
  context_key text NOT NULL DEFAULT '',
  school_code text NOT NULL,
  match_source text NOT NULL DEFAULT 'official-directory',
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.product_vendor_links (
  product_id text PRIMARY KEY,
  vendor_id bigint NOT NULL,
  vendor_name_snapshot text NOT NULL DEFAULT '',
  updated_by bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.product_supply_settings (
  product_id text PRIMARY KEY,
  supply_type text NOT NULL DEFAULT 'partner',
  margin_rate double precision,
  updated_by bigint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS activity_change_batches_created_idx
  ON public.activity_change_batches (created_at DESC);
CREATE INDEX IF NOT EXISTS activity_change_items_activity_idx
  ON public.activity_change_items (activity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS data_control_events_created_idx
  ON public.data_control_events (created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS organization_school_links_org_idx
  ON public.organization_school_links (organization_key, context_key);
CREATE INDEX IF NOT EXISTS organization_school_links_school_idx
  ON public.organization_school_links (school_code);
CREATE INDEX IF NOT EXISTS product_vendor_links_vendor_idx
  ON public.product_vendor_links (vendor_id, product_id);
CREATE INDEX IF NOT EXISTS product_supply_settings_type_idx
  ON public.product_supply_settings (supply_type, product_id);

CREATE TABLE IF NOT EXISTS public.api_credentials (
  id integer PRIMARY KEY CHECK (id = 1),
  encrypted_key text NOT NULL,
  iv text NOT NULL,
  key_last4 text NOT NULL,
  model text NOT NULL,
  updated_by bigint REFERENCES public.members(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.replication_sync_state (
  id integer PRIMARY KEY CHECK (id = 1),
  source_origin text NOT NULL DEFAULT '',
  source_created_at timestamptz,
  source_checksum text NOT NULL DEFAULT '',
  source_counts_json text NOT NULL DEFAULT '{}',
  status text NOT NULL DEFAULT 'idle'
    CHECK (status IN ('idle', 'syncing', 'succeeded', 'failed')),
  last_attempt_at timestamptz,
  last_success_at timestamptz,
  duration_ms integer,
  error_message text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS members_sales_idx
  ON public.members (status, is_sales, display_name);
CREATE INDEX IF NOT EXISTS activities_organization_date_idx
  ON public.activities (organization, activity_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS activities_organization_round_date_idx
  ON public.activities
  (organization, business_round, activity_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS activities_organization_round_manager_date_idx
  ON public.activities
  (organization, business_round, progress_manager, activity_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS activities_date_idx
  ON public.activities (activity_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS activities_manager_created_idx
  ON public.activities (progress_manager, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ai_recommendations_org_idx
  ON public.ai_recommendations (organization, updated_at);
CREATE INDEX IF NOT EXISTS manager_alert_ack_snoozed_idx
  ON public.manager_alert_acknowledgements (member_id, snoozed_until);
CREATE INDEX IF NOT EXISTS activity_review_ack_snoozed_idx
  ON public.activity_review_acknowledgements (member_id, snoozed_until);
CREATE INDEX IF NOT EXISTS activity_assignment_history_activity_idx
  ON public.activity_assignment_history (activity_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS sales_campaigns_name_idx
  ON public.sales_campaigns (name);
CREATE UNIQUE INDEX IF NOT EXISTS sales_campaign_targets_campaign_org_idx
  ON public.sales_campaign_targets (campaign_id, organization);
CREATE INDEX IF NOT EXISTS sales_campaign_targets_assignee_idx
  ON public.sales_campaign_targets (assigned_member_id, campaign_id);
CREATE INDEX IF NOT EXISTS sales_campaign_targets_org_round_campaign_idx
  ON public.sales_campaign_targets
  (organization, business_round, campaign_id);

DROP TRIGGER IF EXISTS ai_recommendations_touch_updated_at
  ON public.ai_recommendations;
CREATE TRIGGER ai_recommendations_touch_updated_at
BEFORE UPDATE ON public.ai_recommendations
FOR EACH ROW EXECUTE FUNCTION security.touch_updated_at();

DROP TRIGGER IF EXISTS manager_alert_ack_touch_updated_at
  ON public.manager_alert_acknowledgements;
CREATE TRIGGER manager_alert_ack_touch_updated_at
BEFORE UPDATE ON public.manager_alert_acknowledgements
FOR EACH ROW EXECUTE FUNCTION security.touch_updated_at();

DROP TRIGGER IF EXISTS activity_review_ack_touch_updated_at
  ON public.activity_review_acknowledgements;
CREATE TRIGGER activity_review_ack_touch_updated_at
BEFORE UPDATE ON public.activity_review_acknowledgements
FOR EACH ROW EXECUTE FUNCTION security.touch_updated_at();

ALTER TABLE public.vercel_schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manager_alert_acknowledgements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_review_acknowledgements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_assignment_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_change_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_change_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_control_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_school_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_vendor_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_supply_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.replication_sync_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.joint_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.joint_project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.joint_project_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.construction_schedule_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.authored_quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complex_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complex_project_budget_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complex_project_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complex_project_item_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complex_project_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complex_project_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.vercel_schema_migrations
  FROM anon, authenticated;
REVOKE ALL ON public.ai_recommendations
  FROM anon, authenticated;
REVOKE ALL ON public.manager_alert_acknowledgements
  FROM anon, authenticated;
REVOKE ALL ON public.activity_review_acknowledgements
  FROM anon, authenticated;
REVOKE ALL ON public.activity_assignment_history
  FROM anon, authenticated;
REVOKE ALL ON public.activity_change_batches
  FROM anon, authenticated;
REVOKE ALL ON public.activity_change_items
  FROM anon, authenticated;
REVOKE ALL ON public.data_control_events
  FROM anon, authenticated;
REVOKE ALL ON public.organization_school_links
  FROM anon, authenticated;
REVOKE ALL ON public.product_vendor_links
  FROM anon, authenticated;
REVOKE ALL ON public.product_supply_settings
  FROM anon, authenticated;
REVOKE ALL ON public.api_credentials
  FROM anon, authenticated;
REVOKE ALL ON public.replication_sync_state
  FROM anon, authenticated;
REVOKE ALL ON public.joint_projects
  FROM anon, authenticated;
REVOKE ALL ON public.joint_project_members
  FROM anon, authenticated;
REVOKE ALL ON public.joint_project_events
  FROM anon, authenticated;
REVOKE ALL ON public.inventory_products
  FROM anon, authenticated;
REVOKE ALL ON public.inventory_transactions
  FROM anon, authenticated;
REVOKE ALL ON public.organization_schedules
  FROM anon, authenticated;
REVOKE ALL ON public.construction_schedule_projects
  FROM anon, authenticated;
REVOKE ALL ON public.authored_quotations
  FROM anon, authenticated;
REVOKE ALL ON public.complex_projects
  FROM anon, authenticated;
REVOKE ALL ON public.complex_project_budget_links
  FROM anon, authenticated;
REVOKE ALL ON public.complex_project_zones
  FROM anon, authenticated;
REVOKE ALL ON public.complex_project_item_details
  FROM anon, authenticated;
REVOKE ALL ON public.complex_project_deliveries
  FROM anon, authenticated;
REVOKE ALL ON public.complex_project_events
  FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public
  FROM anon, authenticated;

UPDATE public.activities
SET execution_type = '직영', consortium_company = ''
WHERE execution_type IS NULL
   OR execution_type = ''
   OR execution_type = '미정';

INSERT INTO public.product_supply_settings (
  product_id, supply_type, margin_rate, updated_by
) VALUES ('quote-62', 'direct', 0.5545454545454546, 0)
ON CONFLICT (product_id) DO NOTHING;

DELETE FROM public.product_vendor_links
WHERE product_id IN (
  SELECT product_id
  FROM public.product_supply_settings
  WHERE supply_type = 'direct'
);

UPDATE public.equipment_items
SET supply_type = 'direct',
    margin_rate = (
      SELECT margin_rate
      FROM public.product_supply_settings
      WHERE product_id = equipment_items.catalog_item_id
    ),
    commission_rate = NULL,
    supplier_vendor_id = NULL,
    supplier_vendor_name = '',
    updated_at = CURRENT_TIMESTAMP
WHERE status IN ('제안 예정', '제안', '견적')
  AND COALESCE(supply_type, 'partner') = 'partner'
  AND catalog_item_id IN (
    SELECT product_id
    FROM public.product_supply_settings
    WHERE supply_type = 'direct'
  );

INSERT INTO public.vercel_schema_migrations (version)
VALUES ('${VERCEL_SCHEMA_VERSION}')
ON CONFLICT (version) DO NOTHING;
`;
