begin;

create extension if not exists pgcrypto;
create schema if not exists security;
revoke all on schema security from public, anon, authenticated;

create or replace function security.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  sync_id uuid not null default gen_random_uuid() unique,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  email text not null unique,
  display_name text not null,
  role text not null default 'member'
    check (role in ('admin', 'assistant', 'member')),
  permissions jsonb not null default '[]'::jsonb
    check (jsonb_typeof(permissions) = 'array'),
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'suspended')),
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by bigint references public.members(id) on delete set null,
  last_seen_at timestamptz not null default now()
);

create unique index if not exists members_email_lower_idx
  on public.members (lower(email));
create index if not exists members_status_idx
  on public.members (status, created_at);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  sync_id uuid not null default gen_random_uuid() unique,
  seed_key text unique,
  activity_date text,
  date_confidence text not null default '확정',
  activity_type text not null,
  category text not null default '외부',
  contact_method text not null default '',
  region text not null default '',
  organization text not null,
  budget_type text not null default '',
  budget_amount text not null default '',
  topic text not null default '',
  summary text not null default '',
  status text not null default '진행 중',
  temperature text not null default '중간',
  award_status text not null default '미정'
    check (award_status in ('미정', '위즈업 수주', '타업체 수주')),
  award_company text not null default '',
  execution_type text not null default '미정'
    check (execution_type in ('미정', '직영', '컨소')),
  consortium_company text not null default '',
  award_stage text not null default '미정'
    check (award_stage in ('미정', '품의', '협상', '계약', '일정 조율', '완공', '검수', '교육')),
  progress_manager text not null default '',
  follow_up_required boolean not null default true,
  follow_up_date text,
  next_action text not null default '',
  progress_schedule text not null default '',
  contact_name text not null default '',
  contact_phone text not null default '',
  contact_email text not null default '',
  source_chat text not null default 'ChatGPT 전체 내보내기',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists activities_organization_idx
  on public.activities (organization);
create index if not exists activities_follow_up_idx
  on public.activities (follow_up_required, follow_up_date);
create index if not exists activities_award_idx
  on public.activities (award_status, organization);

create table if not exists public.activity_authors (
  activity_id bigint primary key
    references public.activities(id) on delete cascade,
  member_id bigint references public.members(id) on delete set null,
  created_by_name text not null,
  created_at timestamptz not null default now()
);
create index if not exists activity_authors_member_idx
  on public.activity_authors (member_id);

create table if not exists public.oauth_clients (
  id bigint generated by default as identity primary key,
  client_id text not null unique,
  client_secret_hash text not null,
  name text not null,
  created_by bigint not null
    references public.members(id) on delete restrict,
  created_at timestamptz not null default now(),
  rotated_at timestamptz
);

create table if not exists public.oauth_codes (
  code_hash text primary key,
  client_id text not null
    references public.oauth_clients(client_id) on delete cascade,
  member_id bigint not null
    references public.members(id) on delete cascade,
  redirect_uri text not null,
  scope text not null default 'activities:write',
  code_challenge text,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists oauth_codes_expiry_idx
  on public.oauth_codes (expires_at, used_at);
create index if not exists oauth_codes_member_idx
  on public.oauth_codes (member_id);

create table if not exists public.oauth_tokens (
  access_token_hash text primary key,
  refresh_token_hash text not null unique,
  client_id text not null
    references public.oauth_clients(client_id) on delete cascade,
  member_id bigint not null
    references public.members(id) on delete cascade,
  scope text not null default 'activities:write',
  expires_at timestamptz not null,
  refresh_expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists oauth_tokens_member_idx
  on public.oauth_tokens (member_id, revoked_at);
create index if not exists oauth_tokens_active_client_idx
  on public.oauth_tokens (client_id)
  where revoked_at is null;

create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_by bigint references public.members(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_locations (
  organization text primary key,
  sync_id uuid not null default gen_random_uuid() unique,
  region text not null default '',
  address text not null default '',
  road_address text not null default '',
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  place_name text not null default '',
  place_id text not null default '',
  updated_by bigint references public.members(id) on delete set null,
  updated_at timestamptz not null default now()
);
create index if not exists organization_locations_region_idx
  on public.organization_locations (region, organization);

create table if not exists public.sales_campaigns (
  id bigint generated by default as identity primary key,
  sync_id uuid not null default gen_random_uuid() unique,
  name text not null unique,
  notes text not null default '',
  created_by bigint not null
    references public.members(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales_campaign_targets (
  id bigint generated by default as identity primary key,
  sync_id uuid not null default gen_random_uuid() unique,
  campaign_id bigint not null
    references public.sales_campaigns(id) on delete cascade,
  organization text not null,
  region text not null default '',
  address text not null default '',
  phone text not null default '',
  contact_name text not null default '',
  notes text not null default '',
  assigned_member_id bigint
    references public.members(id) on delete set null,
  activity_id bigint
    references public.activities(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_id, organization)
);
create index if not exists sales_campaign_targets_assignee_idx
  on public.sales_campaign_targets (assigned_member_id, campaign_id);
create index if not exists sales_campaign_targets_activity_idx
  on public.sales_campaign_targets (activity_id);

create table if not exists public.equipment_projects (
  id bigint generated by default as identity primary key,
  sync_id uuid not null default gen_random_uuid() unique,
  organization text not null,
  name text not null,
  status text not null default '제안',
  budget_type text not null default '',
  notes text not null default '',
  created_by bigint not null
    references public.members(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization, name)
);
create index if not exists equipment_projects_org_idx
  on public.equipment_projects (organization, updated_at);

create table if not exists public.equipment_items (
  id bigint generated by default as identity primary key,
  sync_id uuid not null default gen_random_uuid() unique,
  project_id bigint not null
    references public.equipment_projects(id) on delete cascade,
  product_name text not null,
  specification text not null default '',
  proposed_qty integer not null default 0
    check (proposed_qty between 0 and 999999),
  awarded_qty integer not null default 0
    check (awarded_qty between 0 and 999999),
  installed_qty integer not null default 0
    check (installed_qty between 0 and 999999),
  unit text not null default '대',
  status text not null default '제안',
  notes text not null default '',
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists equipment_items_project_idx
  on public.equipment_items (project_id, sort_order, id);

drop trigger if exists activities_touch_updated_at on public.activities;
create trigger activities_touch_updated_at
before update on public.activities
for each row execute function security.touch_updated_at();

drop trigger if exists app_settings_touch_updated_at on public.app_settings;
create trigger app_settings_touch_updated_at
before update on public.app_settings
for each row execute function security.touch_updated_at();

drop trigger if exists organization_locations_touch_updated_at on public.organization_locations;
create trigger organization_locations_touch_updated_at
before update on public.organization_locations
for each row execute function security.touch_updated_at();

drop trigger if exists sales_campaigns_touch_updated_at on public.sales_campaigns;
create trigger sales_campaigns_touch_updated_at
before update on public.sales_campaigns
for each row execute function security.touch_updated_at();

drop trigger if exists sales_campaign_targets_touch_updated_at on public.sales_campaign_targets;
create trigger sales_campaign_targets_touch_updated_at
before update on public.sales_campaign_targets
for each row execute function security.touch_updated_at();

drop trigger if exists equipment_projects_touch_updated_at on public.equipment_projects;
create trigger equipment_projects_touch_updated_at
before update on public.equipment_projects
for each row execute function security.touch_updated_at();

drop trigger if exists equipment_items_touch_updated_at on public.equipment_items;
create trigger equipment_items_touch_updated_at
before update on public.equipment_items
for each row execute function security.touch_updated_at();

alter table public.members enable row level security;
alter table public.activities enable row level security;
alter table public.activity_authors enable row level security;
alter table public.oauth_clients enable row level security;
alter table public.oauth_codes enable row level security;
alter table public.oauth_tokens enable row level security;
alter table public.app_settings enable row level security;
alter table public.organization_locations enable row level security;
alter table public.sales_campaigns enable row level security;
alter table public.sales_campaign_targets enable row level security;
alter table public.equipment_projects enable row level security;
alter table public.equipment_items enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

commit;
