begin;

create table if not exists public.vercel_schema_migrations (
  version text primary key,
  applied_at timestamptz not null default now()
);

alter table public.members
  add column if not exists is_sales smallint not null default 0;

alter table public.activities
  add column if not exists contact_role text not null default '';

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'activities'
      and column_name = 'follow_up_required'
      and data_type = 'boolean'
  ) then
    alter table public.activities alter column follow_up_required drop default;
    alter table public.activities
      alter column follow_up_required type smallint
      using case when follow_up_required then 1 else 0 end;
    alter table public.activities alter column follow_up_required set default 1;
  end if;
end
$$;

create table if not exists public.ai_recommendations (
  id bigint generated by default as identity primary key,
  activity_id bigint not null unique
    references public.activities(id) on delete cascade,
  organization text not null,
  meeting_summary text not null default '',
  interests_json text not null default '[]',
  recommended_products_json text not null default '[]',
  follow_up_questions_json text not null default '[]',
  recommended_actions_json text not null default '[]',
  applied_products_json text not null default '[]',
  applied_questions_json text not null default '[]',
  applied_actions_json text not null default '[]',
  follow_up_date text,
  created_by bigint not null
    references public.members(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.manager_alert_acknowledgements (
  id bigint generated by default as identity primary key,
  member_id bigint not null
    references public.members(id) on delete cascade,
  organization text not null,
  issue_signature text not null,
  snoozed_until text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (member_id, organization)
);

create table if not exists public.activity_review_acknowledgements (
  id bigint generated by default as identity primary key,
  member_id bigint not null
    references public.members(id) on delete cascade,
  activity_id bigint not null
    references public.activities(id) on delete cascade,
  issue_signature text not null,
  snoozed_until text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (member_id, activity_id)
);

create table if not exists public.activity_assignment_history (
  id bigint generated by default as identity primary key,
  activity_id bigint not null
    references public.activities(id) on delete cascade,
  from_manager text not null default '',
  to_member_id bigint not null
    references public.members(id) on delete restrict,
  to_manager text not null,
  changed_by_member_id bigint not null
    references public.members(id) on delete restrict,
  changed_by_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.api_credentials (
  id integer primary key check (id = 1),
  encrypted_key text not null,
  iv text not null,
  key_last4 text not null,
  model text not null,
  updated_by bigint references public.members(id) on delete set null,
  updated_at timestamptz not null default now()
);

create index if not exists members_sales_idx
  on public.members (status, is_sales, display_name);
create index if not exists activities_organization_date_idx
  on public.activities (organization, activity_date desc, id desc);
create index if not exists activities_date_idx
  on public.activities (activity_date desc, id desc);
create index if not exists activities_manager_created_idx
  on public.activities (progress_manager, created_at desc, id desc);
create index if not exists ai_recommendations_org_idx
  on public.ai_recommendations (organization, updated_at);
create index if not exists manager_alert_ack_snoozed_idx
  on public.manager_alert_acknowledgements (member_id, snoozed_until);
create index if not exists activity_review_ack_snoozed_idx
  on public.activity_review_acknowledgements (member_id, snoozed_until);
create index if not exists activity_assignment_history_activity_idx
  on public.activity_assignment_history (activity_id, created_at);

drop trigger if exists ai_recommendations_touch_updated_at
  on public.ai_recommendations;
create trigger ai_recommendations_touch_updated_at
before update on public.ai_recommendations
for each row execute function security.touch_updated_at();

drop trigger if exists manager_alert_ack_touch_updated_at
  on public.manager_alert_acknowledgements;
create trigger manager_alert_ack_touch_updated_at
before update on public.manager_alert_acknowledgements
for each row execute function security.touch_updated_at();

drop trigger if exists activity_review_ack_touch_updated_at
  on public.activity_review_acknowledgements;
create trigger activity_review_ack_touch_updated_at
before update on public.activity_review_acknowledgements
for each row execute function security.touch_updated_at();

alter table public.vercel_schema_migrations enable row level security;
alter table public.ai_recommendations enable row level security;
alter table public.manager_alert_acknowledgements enable row level security;
alter table public.activity_review_acknowledgements enable row level security;
alter table public.activity_assignment_history enable row level security;
alter table public.api_credentials enable row level security;

revoke all on public.vercel_schema_migrations from anon, authenticated;
revoke all on public.ai_recommendations from anon, authenticated;
revoke all on public.manager_alert_acknowledgements from anon, authenticated;
revoke all on public.activity_review_acknowledgements from anon, authenticated;
revoke all on public.activity_assignment_history from anon, authenticated;
revoke all on public.api_credentials from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

update public.activities
set execution_type = '직영', consortium_company = ''
where execution_type is null
   or execution_type = ''
   or execution_type = '미정';

insert into public.vercel_schema_migrations (version)
values ('202607200001_sites_v94_parallel')
on conflict (version) do nothing;

commit;
